name: para_ya
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.7.0
  country_code_picker: ^3.0.0
  image_picker: ^1.1.2
  flutterfire_cli: ^0.1.1+2
  firebase_core: ^3.8.1
  google_sign_in: ^6.2.1
  firebase_auth: ^5.2.0
  cloud_firestore: ^5.3.0
  firebase_storage: ^12.3.1
  permission_handler: ^11.3.1
  uuid: ^4.5.0
  change_app_package_name: ^1.4.0
  firebase_app_check: ^0.3.1+4
  flutter_facebook_auth: ^6.0.4
  firebase_messaging: ^15.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets: 
    - assets/images/cityfondo.webp
    - assets/images/logo.webp