// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpI9a7ZLlgIkDrC00DSabcJMai1vgiYyc',
    appId: '1:760053968845:web:556d81e638d295b0281e84',
    messagingSenderId: '760053968845',
    projectId: 'para-ya-8d158',
    authDomain: 'para-ya-8d158.firebaseapp.com',
    storageBucket: 'para-ya-8d158.appspot.com',
    measurementId: 'G-Q4KETT4S2J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAE2GFC9d4bHZ9hwEjwetC9os-vHA-cL0A',
    appId: '1:760053968845:android:fa978a0d662873eb281e84',
    messagingSenderId: '760053968845',
    projectId: 'para-ya-8d158',
    storageBucket: 'para-ya-8d158.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAz3KgvcwFYQjU3T_7wWhvm2ASZVsfpv6M',
    appId: '1:760053968845:ios:274ee803d7d8318a281e84',
    messagingSenderId: '760053968845',
    projectId: 'para-ya-8d158',
    storageBucket: 'para-ya-8d158.appspot.com',
    iosBundleId: 'com.example.paraYa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAz3KgvcwFYQjU3T_7wWhvm2ASZVsfpv6M',
    appId: '1:760053968845:ios:274ee803d7d8318a281e84',
    messagingSenderId: '760053968845',
    projectId: 'para-ya-8d158',
    storageBucket: 'para-ya-8d158.appspot.com',
    iosBundleId: 'com.example.paraYa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpI9a7ZLlgIkDrC00DSabcJMai1vgiYyc',
    appId: '1:760053968845:web:3c563f69e1977b76281e84',
    messagingSenderId: '760053968845',
    projectId: 'para-ya-8d158',
    authDomain: 'para-ya-8d158.firebaseapp.com',
    storageBucket: 'para-ya-8d158.appspot.com',
    measurementId: 'G-95X06G15CQ',
  );
}
