// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdiaR1vpcXp0hNncR_N6exsx_nEe0cuy0',
    appId: '1:643480023034:web:a60f44a27105983fc7be43',
    messagingSenderId: '643480023034',
    projectId: 'para-ya-28de5',
    authDomain: 'para-ya-28de5.firebaseapp.com',
    storageBucket: 'para-ya-28de5.appspot.com',
    measurementId: 'G-47V9Z18FLB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAViWStz5M4OkJ1ogJrYjJYqFD9cqDlCEI',
    appId: '1:643480023034:android:be552201c40ec63dc7be43',
    messagingSenderId: '643480023034',
    projectId: 'para-ya-28de5',
    storageBucket: 'para-ya-28de5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5goKgo6JL5mfJgxQBcOZzt1rZpmW70g8',
    appId: '1:643480023034:ios:1af9884b5589f03cc7be43',
    messagingSenderId: '643480023034',
    projectId: 'para-ya-28de5',
    storageBucket: 'para-ya-28de5.appspot.com',
    iosBundleId: 'com.example.paraYa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5goKgo6JL5mfJgxQBcOZzt1rZpmW70g8',
    appId: '1:643480023034:ios:1af9884b5589f03cc7be43',
    messagingSenderId: '643480023034',
    projectId: 'para-ya-28de5',
    storageBucket: 'para-ya-28de5.appspot.com',
    iosBundleId: 'com.example.paraYa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdiaR1vpcXp0hNncR_N6exsx_nEe0cuy0',
    appId: '1:643480023034:web:eaa19c16bc6203ffc7be43',
    messagingSenderId: '643480023034',
    projectId: 'para-ya-28de5',
    authDomain: 'para-ya-28de5.firebaseapp.com',
    storageBucket: 'para-ya-28de5.appspot.com',
    measurementId: 'G-RZN6RWCZNZ',
  );

}